### ISSUE TITLE
Broken Headers

### ISSUE THREAD

**Issue by PERRETJonatan** [jtyszkiew/ImageSmith#4]
Hi, 

I get this error :
```bash
ERROR    Failed to connect to ComfyUI instance http://127.0.0.1:8188: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers' client.py:93
ERROR    Failed to connect to ComfyUI: Failed to connect to any ComfyUI instance                               imagesmith.py:56
```
I tried to edit the code and removing this at line 93 of client.py fixed it
```bash
'extra_headers': ws_headers,
```
I guess these headers are important for authentication but they are broken for now

Have a nice day

**Comment by jtyszkiew** [comment]
Hello, do you have current master? I've changed the requirements file, since there was `websockets>=10` but the configuration you mentioned is removed from never versions. Currently it's set to websockets==12 and it should work. 

I will need to upgrade the websockets lib in the future tho.
